name: 24/7 Lofi Stream
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg
      - name: Start Streaming
        run: |
          ffmpeg -re -loop 1 -i background.jpg -i audio.mp3 -c:v libx264 -preset veryfast -b:v 2000k -maxrate 2000k -bufsize 4000k -pix_fmt yuv420p -g 60 -c:a aac -b:a 128k -ar 44100 -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.YOUTUBE_STREAM_KEY }}"
